# DDP
gpus: "0,1,2,3"
flag: train

# Log
log_dir: "./log/deepfake_iml_vit_train"

# Task
if_predict_label: true
if_predict_mask: false

iml_config: '/mnt/data1/xuekang/workspace/ForensicHub/ForensicHub/statics/deepfake/iml_vit_config.yaml'

rgb_dir : '/mnt/data1/public_datasets/Deepfake'

dataset_json_folder : '/mnt/data1/public_datasets/Deepfake'

all_dataset: [FaceForensics++, FF-F2F, FF-DF, FF-FS, FF-NT, FaceShifter, DeepFakeDetection, Celeb-DF-v1, Celeb-DF-v2, DFDCP, DFDC, DeeperForensics-1.0, UADFV，'FaceForensics++_c40']
train_dataset: [FaceForensics++]
test_dataset: [FaceForensics++_c40, FF-DF, FF-F2F,  FF-FS, FF-NT, Celeb-DF-v1, Celeb-DF-v2, DeepFakeDetection, DFDC, DFDCP, FaceShifter, UADFV]
# test_dataset: [FF-DF, FF-F2F,  FF-FS, FF-NT, Celeb-DF-v1, Celeb-DF-v2, DeepFakeDetection, DFDC, DFDCP, FaceShifter, UADFV]


compression: c23  # compression-level for videos
train_batchSize: 32   # training batch size
test_batchSize: 32   # test batch size
workers: 8   # number of data loading workers
frame_num: {'train': 32, 'test': 32}   # number of frames to use per video in training and testing
resolution: 256   # resolution of output image to network
with_mask: false   # whether to include mask information in the input
with_landmark: false   # whether to include facial landmark information in the input

# Training related
batch_size: 32
test_batch_size: 32
epochs: 10
accum_iter: 1

# Test related
no_model_eval: false
test_period: 1

# Logging & TensorBoard
log_per_epoch_count: 1

# DDP & AMP settings
find_unused_parameters: true
if_not_amp: true

# Optimizer parameters
weight_decay: 0.0005
lr: 2e-4
blr: 0.001
min_lr: 2e-4
warmup_epochs: 0

# Device and training control
device: "cuda"
seed: 42
resume: ""
start_epoch: 0
num_workers: 8
pin_mem: true

# Distributed training parameters
world_size: 1
local_rank: -1
dist_on_itp: false
dist_url: "env://"

ddp: true

label_dict:
  # DFD
  DFD_fake: 1
  DFD_real: 0
  # FF++ + FaceShifter(FF-real+FF-FH)
  FF-SH: 1
  FF-F2F: 1
  FF-DF: 1
  FF-FS: 1
  FF-NT: 1
  FF-FH: 1
  FF-real: 0
  # CelebDF
  CelebDFv1_real: 0
  CelebDFv1_fake: 1
  CelebDFv2_real: 0
  CelebDFv2_fake: 1
  # DFDCP
  DFDCP_Real: 0
  DFDCP_FakeA: 1
  DFDCP_FakeB: 1
  # DFDC
  DFDC_Fake: 1
  DFDC_Real: 0
  # DeeperForensics-1.0
  DF_fake: 1
  DF_real: 0
  # UADFV
  UADFV_Fake: 1
  UADFV_Real: 0
  # Roop
  roop_Real: 0
  roop_Fake: 1

use_data_augmentation: true  # Add this flag to enable/disable data augmentation
data_aug:
  flip_prob: 0.5
  rotate_prob: 0.5
  rotate_limit: [-10, 10]
  blur_prob: 0.5
  blur_limit: [3, 7]
  brightness_prob: 0.5
  brightness_limit: [-0.1, 0.1]
  contrast_limit: [-0.1, 0.1]
  quality_lower: 40
  quality_upper: 100


# mean and std for normalization
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]