# DDP
gpus: "0,1,2,3,4,5,6,7"
flag: train

# Log
log_dir: "./log/rtm/doc_catnet_train"

# Task
if_predict_label: false
if_predict_mask: true

# Model
model:
  name: Cat_Net
  init_config:
    cfg_file: /mnt/data0/xuekang/workspace/ForensicHub/ForensicHub/statics/document/cat_net.yaml


# Transform
transform:
  name: DocTransform
  init_config:
    norm_type: image_net

# Evaluators
evaluator:
  - name: PixelF1
    init_config:
      threshold: 0.5

# Training related
batch_size: 20
test_batch_size: 8
epochs: 200
accum_iter: 1
record_epoch: 0  # Save the best only after record epoch.

# Test related
no_model_eval: false
test_period: 1

# Logging & TensorBoard
log_per_epoch_count: 20

# DDP & AMP settings
find_unused_parameters: true
use_amp: true

# Optimizer parameters
opt: 'AdamW'
weight_decay: 0.05
lr: 1e-4
blr: 0.001
min_lr: 5e-7
warmup_epochs: 1

# Device and training control
device: "cuda"
seed: 42
resume: ""
start_epoch: 0
num_workers: 8
pin_mem: true

# Distributed training parameters
world_size: 1
local_rank: -1
dist_on_itp: false
dist_url: "env://"

